version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2017
platform: Any CPU
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build:
  project: /src/
  parallel: true
  verbosity: minimal
