export const API_REQUEST_BEGIN = 'API_REQUEST_BEGIN'
export const API_REQUEST_END = 'API_REQUEST_END'
export const API_REQUEST_ERROR = 'API_REQUEST_ERROR'

export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE'

export const MENU_TOOGLE = 'MENU_TOOGLE'

export const BOOK_SEARCH_ADD = 'BOOK_SEARCH_ADD'
export const BOOK_SEARCH_REMOVE = 'BOOK_SEARCH_REMOVE'
export const BOOK_SEARCH_RETRIVED = 'BOOK_SEARCH_RETRIVED'
export const BOOK_SEARCH_CLEAR = 'BOOK_SEARCH_CLEAR'
export const BOOK_SEARCH_NOT_FOUND = 'BOOK_SEARCH_NOT_FOUND'

export const SNACKBAR_OPEN = 'SNACKBAR_OPEN'
export const SNACKBAR_CLOSE = 'SNACKBAR_OPEN'

export const RULE_CHANGE = 'RULE_CHANGE'
export const RULE_REMOVED = 'RULE_REMOVED'
export const RULE_ADDED = 'RULE_ADDED'