export const API_REQUEST_BEGIN = 'API_REQUEST_BEGIN'
export const API_REQUEST_END = 'API_REQUEST_END'
export const API_REQUEST_ERROR = 'API_REQUEST_ERROR'

export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE'

export const MENU_TOOGLE = 'MENU_TOOGLE'

export const ADD_BOOK_SEARCH = 'ADD_BOOK_SEARCH'
export const REMOVE_BOOK_SEARCH = 'REMOVE_BOOK_SEARCH'