// <auto-generated />
using BookTracker.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace BookTracker.Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180210053353_adding_boxes_config_and_minbox")]
    partial class adding_boxes_config_and_minbox
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("BookTracker.Models.System.Box", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Color");

                    b.Property<string>("Description");

                    b.Property<bool>("Enabled");

                    b.Property<int>("MaxSalesRank");

                    b.Property<int>("MaxSalesRank1");

                    b.Property<int>("MaxSalesRank2");

                    b.Property<int>("MaxSalesRank3");

                    b.Property<decimal>("MinNetPayout");

                    b.Property<decimal>("MinNetPayout1");

                    b.Property<decimal>("MinNetPayout2");

                    b.Property<decimal>("MinNetPayout3");

                    b.Property<int>("MinSalesRank");

                    b.Property<int>("MinSalesRank1");

                    b.Property<int>("MinSalesRank2");

                    b.Property<int>("MinSalesRank3");

                    b.Property<string>("Name");

                    b.Property<string>("SoundPath");

                    b.HasKey("Id");

                    b.ToTable("BoxConfig");
                });

            modelBuilder.Entity("BookTracker.Models.System.MinBox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Color");

                    b.Property<bool>("Enabled");

                    b.Property<decimal>("OfferGreaterThan");

                    b.Property<string>("Sound");

                    b.HasKey("Id");

                    b.ToTable("MinBoxConfig");
                });

            modelBuilder.Entity("BookTracker.Models.System.SystemConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Current");

                    b.Property<string>("KeepaApiKey");

                    b.Property<DateTime>("LastModified");

                    b.HasKey("Id");

                    b.ToTable("SystemConfig");
                });
#pragma warning restore 612, 618
        }
    }
}
